name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        build: [ linux ]
        include:
          - build: linux
            os: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - name: Install rust nightly
      run: |
        curl -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
        rustup toolchain install nightly-x86_64-unknown-linux-gnu
        rustup target add x86_64-unknown-linux-gnu
        rustup default nightly
    - name: Install pipenv
      run: pip install pipenv
    - name: Run test
      run: make ci
